from bs4 import BeautifulSoup
from textblob import TextBlob
import requests

class Analysis:
	# 'classes' are a set of css classes generated by Google, which defines the <h3> tags that contain headlines
	# these classes change from time to time - news.google.com should be inspected to check which classes are used
	def __init__(self, classes):
		self.classes = classes
		self.sentiment = 0
		self.subjectivity = 0
		self.number_of_news = 0
		self.url = 'https://news.google.com/topics/CAAqJggKIiBDQkFTRWdvSUwyMHZNRGx6TVdZU0FtVnVHZ0pWVXlnQVAB?hl=en-US&gl=US&ceid=US%3Aen'

	def run(self):
		response = requests.get(self.url)
		soup = BeautifulSoup(response.text, 'html.parser')
		news = soup.find_all('h3', class_ = self.classes)
		self.number_of_news = len(news)
		for headline in news:
			blob = TextBlob(headline.get_text())	
			self.sentiment += blob.sentiment.polarity / self.number_of_news
			self.subjectivity += blob.sentiment.subjectivity / self.number_of_news

classes = 'ipQwMb ekueJc gEATFF RD0gLb'
analyser = Analysis(classes)
analyser.run()
print(analyser.sentiment, analyser.subjectivity)